@startuml
!pragma layout smetana
'https://plantuml.com/class-diagram

class Game
class Player


Game *-- Player

class Game {
- String name
- int maxPlayers
- List<Player>
+ Game (String name, int maxPlayers)
- void createPlayers()
+ void registerPlayers()
+ void displayPlayers()

}

class Player {
- String name
- int score
+ Player(String name, int score)
+ String toString()

}

@enduml