@startuml
'https://plantuml.com/sequence-diagram


'Create a list for composing an age appropriate menu
DrinksMenu -> ArrayList:options = new ArrayList()

alt (age < 18)
'DrinksMenu giver options til ArrayList som skriver "Milk" på plads 0
DrinksMenu -> ArrayList:options.add("Milk")
else (false)
DrinksMenu -> ArrayList:options.add("Beer")
end

@enduml